[package]
name = "poker-web"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
rand = "0.10.0"
strum = "0.27.2"
strum_macros = "0.27.2"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }

[lints.rust]
dead_code = "allow"
unused_imports = "allow"
